<template><div><h2 id="mongodb-pymongo" tabindex="-1"><a class="header-anchor" href="#mongodb-pymongo" aria-hidden="true">#</a> MongoDB-pymongo</h2>
<p>导入库 import pymongo</p>
<h3 id="_1-连接数据库" tabindex="-1"><a class="header-anchor" href="#_1-连接数据库" aria-hidden="true">#</a> 1. 连接数据库</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>client<span class="token operator">=</span>pymongo<span class="token punctuation">.</span>MongoClient<span class="token punctuation">(</span>host<span class="token operator">=</span><span class="token string">"localhost"</span><span class="token punctuation">,</span>port<span class="token operator">=</span><span class="token number">27017</span><span class="token punctuation">)</span>
client<span class="token operator">=</span>pymongo<span class="token punctuation">.</span>MongoClient<span class="token punctuation">(</span><span class="token string">'mongodb://localhost:27017/'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-指定数据库" tabindex="-1"><a class="header-anchor" href="#_2-指定数据库" aria-hidden="true">#</a> 2. 指定数据库</h3>
<p>不存在该数据库会自动创建</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>db<span class="token operator">=</span>client<span class="token punctuation">.</span>first
db<span class="token operator">=</span>client<span class="token punctuation">[</span><span class="token string">'first'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-指定集合-数据表" tabindex="-1"><a class="header-anchor" href="#_3-指定集合-数据表" aria-hidden="true">#</a> 3. 指定集合（数据表）</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>collections<span class="token operator">=</span>db<span class="token punctuation">.</span>info
collections<span class="token operator">=</span>db<span class="token punctuation">[</span><span class="token string">'info'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_4-插入数据" tabindex="-1"><a class="header-anchor" href="#_4-插入数据" aria-hidden="true">#</a> 4. 插入数据</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>info<span class="token operator">=</span><span class="token punctuation">{</span>
    <span class="token string">'id'</span><span class="token punctuation">:</span><span class="token string">'123'</span><span class="token punctuation">,</span>
    <span class="token string">'name'</span><span class="token punctuation">:</span><span class="token string">'xiaoyi'</span><span class="token punctuation">,</span>
    <span class="token string">'birth'</span><span class="token punctuation">:</span><span class="token string">'1027'</span><span class="token punctuation">,</span>
     <span class="token string">'sex'</span><span class="token punctuation">:</span><span class="token string">'girl'</span>
<span class="token punctuation">}</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>insert_one<span class="token punctuation">(</span>info<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>result<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_4-1-批量插入数据-insert-one" tabindex="-1"><a class="header-anchor" href="#_4-1-批量插入数据-insert-one" aria-hidden="true">#</a> 4.1 批量插入数据(insert_one)</h4>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code> <span class="token keyword">for</span> num <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">501</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
     info_second <span class="token operator">=</span> <span class="token punctuation">{</span>
         <span class="token string">'name'</span><span class="token punctuation">:</span> faker<span class="token punctuation">.</span>name<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
         <span class="token string">'email'</span><span class="token punctuation">:</span> faker<span class="token punctuation">.</span>email<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
         <span class="token string">'post'</span><span class="token punctuation">:</span> faker<span class="token punctuation">.</span>postcode<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
     <span class="token punctuation">}</span>
     collections<span class="token punctuation">.</span>insert_one<span class="token punctuation">(</span>info_second<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_4-2-批量插入数据-insert-many" tabindex="-1"><a class="header-anchor" href="#_4-2-批量插入数据-insert-many" aria-hidden="true">#</a> 4.2 批量插入数据(insert_many)</h4>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>result<span class="token operator">=</span>collections<span class="token punctuation">.</span>insert_many<span class="token punctuation">(</span><span class="token punctuation">[</span>info<span class="token punctuation">,</span>info_student<span class="token punctuation">]</span><span class="token punctuation">)</span>

new_list<span class="token operator">=</span><span class="token punctuation">[</span><span class="token punctuation">]</span>
<span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">501</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
     daylist <span class="token operator">=</span> <span class="token punctuation">{</span>
         <span class="token string">'name'</span><span class="token punctuation">:</span> faker<span class="token punctuation">.</span>name<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
         <span class="token string">'email'</span><span class="token punctuation">:</span> faker<span class="token punctuation">.</span>email<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
         <span class="token string">'post'</span><span class="token punctuation">:</span> faker<span class="token punctuation">.</span>postcode<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
     <span class="token punctuation">}</span>
     new_list<span class="token punctuation">.</span>append<span class="token punctuation">(</span>daylist<span class="token punctuation">)</span>
 collections<span class="token punctuation">.</span>insert_many<span class="token punctuation">(</span>new_list<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_5-查询数据" tabindex="-1"><a class="header-anchor" href="#_5-查询数据" aria-hidden="true">#</a> 5. 查询数据</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">from</span> bson<span class="token punctuation">.</span>objectid <span class="token keyword">import</span> ObjectId

result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find_one<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"name"</span><span class="token punctuation">:</span><span class="token string">"wewe"</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token comment">#获取所有xiaoyi的信息</span>
result2<span class="token operator">=</span>collections<span class="token punctuation">.</span>find<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"name"</span><span class="token punctuation">:</span><span class="token string">"xiaoyi"</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token comment">#查询不存在的id会返回None</span>
result3<span class="token operator">=</span>collections<span class="token punctuation">.</span>find_one<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"_id"</span><span class="token punctuation">:</span>ObjectId<span class="token punctuation">(</span><span class="token string">"63b4dee4d36d58d5a24b4172"</span><span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_6-查询数据范围-int" tabindex="-1"><a class="header-anchor" href="#_6-查询数据范围-int" aria-hidden="true">#</a> 6. 查询数据范围（int)</h3>
<img src="@source/Blog/2022/MongoDB_/About_MGdb.assets/image-20230105010554145.png" alt="image-20230105010554145" style="zoom: 50%;" />
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find_one<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"birth"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$gt"</span><span class="token punctuation">:</span><span class="token number">8888</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find_one<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"birth"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$in"</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token number">8888</span><span class="token punctuation">,</span><span class="token number">20000</span><span class="token punctuation">]</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find_one<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"birth"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$lt"</span><span class="token punctuation">:</span><span class="token number">10000</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find_one<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"birth"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$lte"</span><span class="token punctuation">:</span><span class="token number">8888</span><span class="token comment">##}})</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_7-查询数据范围-各类属性" tabindex="-1"><a class="header-anchor" href="#_7-查询数据范围-各类属性" aria-hidden="true">#</a> 7. 查询数据范围(各类属性)</h3>
<img src="@source/Blog/2022/MongoDB_/About_MGdb.assets/image-20230105235613406.png" alt="image-20230105235613406" style="zoom: 33%;" />
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find_one<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"name"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$regex"</span><span class="token punctuation">:</span><span class="token string">"^h.*"</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find_one<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"birth"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$type"</span><span class="token punctuation">:</span><span class="token string">"int"</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find_one<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"name"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$exists"</span><span class="token punctuation">:</span><span class="token boolean">True</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>result<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_8-统计" tabindex="-1"><a class="header-anchor" href="#_8-统计" aria-hidden="true">#</a> 8. 统计</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>counts<span class="token operator">=</span>collections<span class="token punctuation">.</span>count_documents<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"sex"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$ne"</span><span class="token punctuation">:</span><span class="token string">"girl"</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>counts<span class="token punctuation">)</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"sex"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$ne"</span><span class="token punctuation">:</span><span class="token string">"girl"</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
num<span class="token operator">=</span><span class="token number">0</span>
<span class="token keyword">for</span> i <span class="token keyword">in</span> result<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span>
    num<span class="token operator">+=</span><span class="token number">1</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>num<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_9-排序" tabindex="-1"><a class="header-anchor" href="#_9-排序" aria-hidden="true">#</a> 9.排序</h3>
<p>字符首字母大小/字符串大小</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>sort<span class="token punctuation">(</span><span class="token string">"birth"</span><span class="token punctuation">,</span>pymongo<span class="token punctuation">.</span>ASCENDING<span class="token punctuation">)</span><span class="token comment">#升序</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>sort<span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">,</span>pymongo<span class="token punctuation">.</span>DESCENDING<span class="token punctuation">)</span><span class="token comment">#降序</span>
<span class="token keyword">for</span> i <span class="token keyword">in</span> result<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_10-偏移" tabindex="-1"><a class="header-anchor" href="#_10-偏移" aria-hidden="true">#</a> 10. 偏移</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>sort<span class="token punctuation">(</span><span class="token string">"birth"</span><span class="token punctuation">,</span>pymongo<span class="token punctuation">.</span>ASCENDING<span class="token punctuation">)</span><span class="token punctuation">.</span>skip<span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span>
跳过前两条数据，从第三条开始获取
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>find<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>sort<span class="token punctuation">(</span><span class="token string">"birth"</span><span class="token punctuation">,</span>pymongo<span class="token punctuation">.</span>ASCENDING<span class="token punctuation">)</span><span class="token punctuation">.</span>skip<span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">.</span>limit<span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span>
跳过前两条<span class="token punctuation">,</span>且只往后获取<span class="token number">2</span>条
<span class="token keyword">for</span> i <span class="token keyword">in</span> result<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_11-数据更新update-set" tabindex="-1"><a class="header-anchor" href="#_11-数据更新update-set" aria-hidden="true">#</a> 11.数据更新update  $set</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>condition<span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">"name"</span><span class="token punctuation">:</span><span class="token string">"mike"</span><span class="token punctuation">}</span>
student<span class="token operator">=</span>collections<span class="token punctuation">.</span>find_one<span class="token punctuation">(</span>condition<span class="token punctuation">)</span>
student<span class="token punctuation">[</span><span class="token string">"birth"</span><span class="token punctuation">]</span><span class="token operator">=</span><span class="token number">24</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>update_one<span class="token punctuation">(</span>condition<span class="token punctuation">,</span><span class="token punctuation">{</span><span class="token string">"$set"</span><span class="token punctuation">:</span>student<span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>result<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_12-指定某个数据增加" tabindex="-1"><a class="header-anchor" href="#_12-指定某个数据增加" aria-hidden="true">#</a> 12. 指定某个数据增加</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>condition<span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">"birth"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$gt"</span><span class="token punctuation">:</span><span class="token number">7</span><span class="token punctuation">}</span><span class="token punctuation">}</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>update_one<span class="token punctuation">(</span>condition<span class="token punctuation">,</span><span class="token punctuation">{</span><span class="token string">"$inc"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"birth"</span><span class="token punctuation">:</span><span class="token number">4</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>update_many<span class="token punctuation">(</span>condition<span class="token punctuation">,</span><span class="token punctuation">{</span><span class="token string">"$inc"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"birth"</span><span class="token punctuation">:</span><span class="token number">4</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>result<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_13-数据删减" tabindex="-1"><a class="header-anchor" href="#_13-数据删减" aria-hidden="true">#</a> 13. 数据删减</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>condition<span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">"birth"</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">"$gt"</span><span class="token punctuation">:</span><span class="token number">30</span><span class="token punctuation">}</span><span class="token punctuation">}</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>delete_one<span class="token punctuation">(</span>condition<span class="token punctuation">)</span>
result<span class="token operator">=</span>collections<span class="token punctuation">.</span>delete_many<span class="token punctuation">(</span>condition<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


