export const data = JSON.parse("{\"key\":\"v-daa77b70\",\"path\":\"/Blog/2022/Gra/About_aiottp.html\",\"title\":\"aiottip\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"aiottip\",\"date\":\"2022-10-30T12:04:21.000Z\",\"author\":\"cava\",\"isOriginal\":true,\"category\":[\"notebook\"],\"tag\":[\"python\",\"爬虫\"],\"icon\":\"vue\",\"sticky\":false,\"star\":false,\"password\":false,\"article\":true,\"timeline\":true,\"image\":false,\"navbar\":true,\"sidebarIcon\":true,\"headerDepth\":5,\"comment\":true,\"lastUpdated\":true,\"editLink\":false,\"backToTop\":true,\"toc\":true,\"summary\":\"aiottp 概念 iohttp 是一个基于 asyncio 的异步 HTTP 网络模块，它既提供了服务端，又提供了客户端。其中我们用服务端可以搭建一个支持异步处理的服务器，用于处理请求并返回响应，类似于 Django、Flask、Tornado 等一些 Web 服务器。而客户端我们就可以用来发起请求，就类似于 requests 来发起一个 HTTP 请求然\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://augwewe.cn/Blog/2022/Gra/About_aiottp.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"augwewe\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"aiottip\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"cava\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"python\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"爬虫\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-10-30T12:04:21.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"aiottp\",\"slug\":\"aiottp\",\"link\":\"#aiottp\",\"children\":[{\"level\":3,\"title\":\"概念\",\"slug\":\"概念\",\"link\":\"#概念\",\"children\":[]},{\"level\":3,\"title\":\"1. attiop基本案例代码\",\"slug\":\"_1-attiop基本案例代码\",\"link\":\"#_1-attiop基本案例代码\",\"children\":[]},{\"level\":3,\"title\":\"3. post表单提交\",\"slug\":\"_3-post表单提交\",\"link\":\"#_3-post表单提交\",\"children\":[]},{\"level\":3,\"title\":\"4. post json数据提交\",\"slug\":\"_4-post-json数据提交\",\"link\":\"#_4-post-json数据提交\",\"children\":[]},{\"level\":3,\"title\":\"5. 返回 响应字段\",\"slug\":\"_5-返回-响应字段\",\"link\":\"#_5-返回-响应字段\",\"children\":[]},{\"level\":3,\"title\":\"6. 超时设置\",\"slug\":\"_6-超时设置\",\"link\":\"#_6-超时设置\",\"children\":[]},{\"level\":3,\"title\":\"7. 控制并发量（Semaphore)\",\"slug\":\"_7-控制并发量-semaphore\",\"link\":\"#_7-控制并发量-semaphore\",\"children\":[]},{\"level\":3,\"title\":\"实战\",\"slug\":\"实战\",\"link\":\"#实战\",\"children\":[]}]}],\"readingTime\":{\"minutes\":5.07,\"words\":1521},\"filePathRelative\":\"Blog/2022/Gra/About_aiottp.md\",\"localizedDate\":\"2022年10月30日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
