<template><div><h2 id="_1-获取request-以文本形式" tabindex="-1"><a class="header-anchor" href="#_1-获取request-以文本形式" aria-hidden="true">#</a> 1.获取request 以文本形式</h2>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>url<span class="token operator">=</span><span class="token string">"https://ssr1.scrape.center/"</span>
response<span class="token operator">=</span>requests<span class="token punctuation">.</span>get<span class="token punctuation">(</span>url<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>response<span class="token punctuation">.</span>text<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_1-1-文本保存" tabindex="-1"><a class="header-anchor" href="#_1-1-文本保存" aria-hidden="true">#</a> 1.1 文本保存</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>url<span class="token operator">=</span><span class="token string">"https://ssr1.scrape.center/"</span>
r<span class="token operator">=</span>requests<span class="token punctuation">.</span>get<span class="token punctuation">(</span>url<span class="token punctuation">,</span>params<span class="token operator">=</span>data<span class="token punctuation">)</span>
pattern1<span class="token operator">=</span>re<span class="token punctuation">.</span><span class="token builtin">compile</span><span class="token punctuation">(</span><span class="token string">"&lt;h2.*?>(.*?)&lt;/h2>"</span><span class="token punctuation">,</span>re<span class="token punctuation">.</span>S<span class="token punctuation">)</span>
result<span class="token operator">=</span>re<span class="token punctuation">.</span>findall<span class="token punctuation">(</span>pattern1<span class="token punctuation">,</span>r<span class="token punctuation">.</span>text<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>result<span class="token punctuation">)</span>
pprint<span class="token punctuation">(</span>r<span class="token punctuation">.</span>json<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token comment">#r.text()</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_1-2-二进制文件-音频-图片" tabindex="-1"><a class="header-anchor" href="#_1-2-二进制文件-音频-图片" aria-hidden="true">#</a> 1.2 二进制文件（音频，图片）</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>url<span class="token operator">=</span><span class="token string">"https://image.cache.storm.mg/styles/smg-800x533-fp/s3/media/image/2016/10/16/20161016-024858_U3250_M207634_e515.jpg"</span>
r<span class="token operator">=</span>requests<span class="token punctuation">.</span>get<span class="token punctuation">(</span>url<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>r<span class="token punctuation">.</span>text<span class="token punctuation">)</span><span class="token comment">#乱码显示</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>r<span class="token punctuation">.</span>content<span class="token punctuation">)</span><span class="token comment">#二进制目标</span>
<span class="token keyword">with</span> <span class="token builtin">open</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'img.</span><span class="token interpolation"><span class="token punctuation">{</span>url<span class="token punctuation">.</span>split<span class="token punctuation">(</span><span class="token string">"."</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">}</span></span><span class="token string">'</span></span><span class="token punctuation">,</span><span class="token string">'wb'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> f<span class="token punctuation">:</span>
    f<span class="token punctuation">.</span>write<span class="token punctuation">(</span>r<span class="token punctuation">.</span>content<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-测试工具-可以看到请求头等信息" tabindex="-1"><a class="header-anchor" href="#_2-测试工具-可以看到请求头等信息" aria-hidden="true">#</a> 2.测试工具：可以看到请求头等信息</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>url<span class="token operator">=</span><span class="token string">"http://httpbin.org/get"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></div></template>


