<template><div><h3 id="爬虫技术-存储网页所有图片" tabindex="-1"><a class="header-anchor" href="#爬虫技术-存储网页所有图片" aria-hidden="true">#</a> 爬虫技术-存储网页所有图片</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">import</span> re<span class="token punctuation">,</span> requests<span class="token punctuation">,</span>cchardet<span class="token punctuation">,</span>urllib<span class="token punctuation">.</span>parse<span class="token punctuation">,</span>traceback
<span class="token keyword">from</span> urllib<span class="token punctuation">.</span>parse <span class="token keyword">import</span> urlparse
<span class="token keyword">from</span> urllib<span class="token punctuation">.</span>parse <span class="token keyword">import</span> urljoin
<span class="token keyword">from</span> requests<span class="token punctuation">.</span>exceptions <span class="token keyword">import</span> RequestException<span class="token punctuation">,</span>ProxyError<span class="token punctuation">,</span>SSLError

<span class="token keyword">class</span> <span class="token class-name">IMGSAVE</span><span class="token punctuation">(</span><span class="token builtin">object</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span>url<span class="token punctuation">)</span><span class="token punctuation">:</span>
        self<span class="token punctuation">.</span>url <span class="token operator">=</span> url

    <span class="token keyword">def</span> <span class="token function">ask_url</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span>url<span class="token punctuation">,</span>headers<span class="token operator">=</span><span class="token boolean">None</span><span class="token punctuation">,</span>timeout<span class="token operator">=</span><span class="token number">10</span><span class="token punctuation">,</span>binary<span class="token operator">=</span><span class="token boolean">False</span><span class="token punctuation">,</span>debug<span class="token operator">=</span><span class="token boolean">False</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token keyword">if</span> <span class="token string">"https"</span> <span class="token keyword">not</span> <span class="token keyword">in</span> url<span class="token punctuation">:</span>
            url <span class="token operator">=</span> <span class="token string">"https://"</span><span class="token operator">+</span>url
        <span class="token keyword">global</span> status<span class="token punctuation">,</span>html<span class="token punctuation">,</span>redirected_url
        the_headers <span class="token operator">=</span> <span class="token punctuation">{</span>
        <span class="token string">"User-Agent"</span><span class="token punctuation">:</span><span class="token string">"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"</span>
    <span class="token punctuation">}</span>
        <span class="token keyword">if</span> headers<span class="token punctuation">:</span>
            the_headers <span class="token operator">=</span> headers
        <span class="token keyword">try</span><span class="token punctuation">:</span>
            response<span class="token operator">=</span>requests<span class="token punctuation">.</span>get<span class="token punctuation">(</span>url<span class="token punctuation">,</span>headers<span class="token operator">=</span>the_headers<span class="token punctuation">,</span>timeout<span class="token operator">=</span>timeout<span class="token punctuation">)</span>
            <span class="token keyword">if</span> response<span class="token punctuation">.</span>status_code <span class="token operator">==</span> <span class="token number">200</span><span class="token punctuation">:</span>
                <span class="token keyword">if</span> binary<span class="token punctuation">:</span>
                    html <span class="token operator">=</span> response<span class="token punctuation">.</span>content
                <span class="token keyword">else</span><span class="token punctuation">:</span>
                    encoding <span class="token operator">=</span> cchardet<span class="token punctuation">.</span>detect<span class="token punctuation">(</span>response<span class="token punctuation">.</span>content<span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token string">'encoding'</span><span class="token punctuation">]</span>
                    html <span class="token operator">=</span> response<span class="token punctuation">.</span>content<span class="token punctuation">.</span>decode<span class="token punctuation">(</span>encoding<span class="token punctuation">)</span>
                status <span class="token operator">=</span> response<span class="token punctuation">.</span>status_code
                redirected_url <span class="token operator">=</span> response<span class="token punctuation">.</span>url

        <span class="token keyword">except</span><span class="token punctuation">(</span>RequestException<span class="token punctuation">,</span>ProxyError<span class="token punctuation">,</span>SSLError<span class="token punctuation">)</span><span class="token keyword">as</span> e<span class="token punctuation">:</span>
            <span class="token keyword">print</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span>
            <span class="token keyword">if</span> debug<span class="token punctuation">:</span>
                traceback<span class="token punctuation">.</span>print_exc<span class="token punctuation">(</span><span class="token punctuation">)</span>
            msg <span class="token operator">=</span> <span class="token string">'Failed downled:{}'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span>
            <span class="token keyword">print</span><span class="token punctuation">(</span>msg<span class="token punctuation">)</span>
            <span class="token keyword">if</span> binary<span class="token punctuation">:</span>
                html <span class="token operator">=</span> <span class="token string">b''</span>
            <span class="token keyword">else</span><span class="token punctuation">:</span>
                html <span class="token operator">=</span> <span class="token string">''</span>
            status<span class="token operator">=</span><span class="token number">0</span>
        <span class="token keyword">return</span> status<span class="token punctuation">,</span>html<span class="token punctuation">,</span>redirected_url

    <span class="token keyword">def</span> <span class="token function">regex</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span>html<span class="token punctuation">)</span><span class="token punctuation">:</span>
        pattern <span class="token operator">=</span> re<span class="token punctuation">.</span><span class="token builtin">compile</span><span class="token punctuation">(</span><span class="token string">'&lt;img.*?src="(.*?)".*?>'</span><span class="token punctuation">,</span>re<span class="token punctuation">.</span>S<span class="token punctuation">)</span>
        result <span class="token operator">=</span> re<span class="token punctuation">.</span>findall<span class="token punctuation">(</span>pattern<span class="token punctuation">,</span>html<span class="token punctuation">)</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span>result<span class="token punctuation">)</span>
        <span class="token keyword">return</span> result

    <span class="token keyword">def</span> <span class="token function">save_img</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span>filename<span class="token punctuation">,</span>content<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token keyword">with</span> <span class="token builtin">open</span><span class="token punctuation">(</span>filename<span class="token punctuation">,</span><span class="token string">"wb"</span><span class="token punctuation">)</span><span class="token keyword">as</span> fb<span class="token punctuation">:</span>
            fb<span class="token punctuation">.</span>write<span class="token punctuation">(</span>content<span class="token punctuation">)</span>

    <span class="token keyword">def</span> <span class="token function">suffix</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span>path<span class="token punctuation">)</span><span class="token punctuation">:</span>
        suffix<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">".png"</span><span class="token punctuation">,</span><span class="token string">".jpg"</span><span class="token punctuation">,</span><span class="token string">".jpge"</span><span class="token punctuation">]</span> <span class="token comment">#可以添加任意后缀到列表中</span>
        <span class="token keyword">for</span> i <span class="token keyword">in</span> suffix<span class="token punctuation">:</span>
            <span class="token keyword">if</span> i <span class="token keyword">not</span> <span class="token keyword">in</span> path<span class="token punctuation">.</span>lower<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
                <span class="token keyword">continue</span>
            <span class="token keyword">return</span>  i
    <span class="token keyword">def</span> <span class="token function">start</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span>url<span class="token punctuation">)</span><span class="token punctuation">:</span>
        status<span class="token punctuation">,</span> html<span class="token punctuation">,</span> redirected_url <span class="token operator">=</span> self<span class="token punctuation">.</span>ask_url<span class="token punctuation">(</span>url<span class="token operator">=</span>url<span class="token punctuation">,</span> debug<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span>
        template <span class="token operator">=</span> <span class="token string">"{scheme}://{netloc}"</span> 
        the_parse <span class="token operator">=</span> urlparse<span class="token punctuation">(</span>redirected_url<span class="token punctuation">)</span>
        url <span class="token operator">=</span> template<span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>scheme<span class="token operator">=</span>the_parse<span class="token punctuation">.</span>scheme<span class="token punctuation">,</span> netloc<span class="token operator">=</span>the_parse<span class="token punctuation">.</span>netloc<span class="token punctuation">)</span>  <span class="token comment"># 指定</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span>
        r_u <span class="token operator">=</span> self<span class="token punctuation">.</span>regex<span class="token punctuation">(</span>html<span class="token punctuation">)</span>  <span class="token comment"># 同下方解析中的path</span>
        <span class="token keyword">if</span> <span class="token keyword">not</span> r_u<span class="token punctuation">:</span>
            <span class="token keyword">pass</span>
        img_urls <span class="token operator">=</span> <span class="token punctuation">[</span>urljoin<span class="token punctuation">(</span>url<span class="token punctuation">,</span> img<span class="token punctuation">)</span> <span class="token keyword">for</span> img <span class="token keyword">in</span> r_u<span class="token punctuation">]</span>
        <span class="token comment"># print(img_urls)</span>
        <span class="token keyword">for</span> index<span class="token punctuation">,</span> url <span class="token keyword">in</span> <span class="token builtin">enumerate</span><span class="token punctuation">(</span>img_urls<span class="token punctuation">)</span><span class="token punctuation">:</span>
            postffix <span class="token operator">=</span> self<span class="token punctuation">.</span>suffix<span class="token punctuation">(</span>url<span class="token punctuation">)</span>
            filename <span class="token operator">=</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>index<span class="token punctuation">}</span></span><span class="token interpolation"><span class="token punctuation">{</span>postffix<span class="token punctuation">}</span></span><span class="token string">'</span></span>
            content <span class="token operator">=</span> self<span class="token punctuation">.</span>ask_url<span class="token punctuation">(</span>url<span class="token punctuation">,</span> debug<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">,</span> binary<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span>
            self<span class="token punctuation">.</span>save_img<span class="token punctuation">(</span>filename<span class="token punctuation">,</span> content<span class="token punctuation">)</span>
<span class="token keyword">def</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    url<span class="token operator">=</span><span class="token string">"www.bbiquge.net"</span>
    work<span class="token operator">=</span>IMGSAVE<span class="token punctuation">(</span>url<span class="token punctuation">)</span>
    work<span class="token punctuation">.</span>start<span class="token punctuation">(</span>url<span class="token punctuation">)</span>
<span class="token keyword">if</span> __name__ <span class="token operator">==</span> <span class="token string">'__main__'</span><span class="token punctuation">:</span>
    main<span class="token punctuation">(</span><span class="token punctuation">)</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="urllib-parse" tabindex="-1"><a class="header-anchor" href="#urllib-parse" aria-hidden="true">#</a> urllib.parse</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">import</span> urllib<span class="token punctuation">.</span>parse

url<span class="token operator">=</span><span class="token string">"https://www.bbiquge.net"</span>
test<span class="token operator">=</span>urllib<span class="token punctuation">.</span>parse<span class="token punctuation">.</span>urlparse<span class="token punctuation">(</span>url<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>test<span class="token punctuation">)</span>
输出<span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span>
ParseResult<span class="token punctuation">(</span>scheme<span class="token operator">=</span><span class="token string">'https'</span><span class="token punctuation">,</span> netloc<span class="token operator">=</span><span class="token string">'bornforthis.cn'</span><span class="token punctuation">,</span> path<span class="token operator">=</span><span class="token string">'/1v1/17-R/01.html'</span><span class="token punctuation">,</span> params<span class="token operator">=</span><span class="token string">''</span><span class="token punctuation">,</span> query<span class="token operator">=</span><span class="token string">''</span><span class="token punctuation">,</span> fragment<span class="token operator">=</span><span class="token string">''</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="处理图片链接模板" tabindex="-1"><a class="header-anchor" href="#处理图片链接模板" aria-hidden="true">#</a> 处理图片链接模板</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>url<span class="token operator">=</span><span class="token string">"https://bornforthis.cn/assets/image-20230104195900212-3876c2ce.pngxxxxxx"</span>
<span class="token keyword">def</span> <span class="token function">suffix</span><span class="token punctuation">(</span>path<span class="token punctuation">)</span><span class="token punctuation">:</span>
    suffix<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">".png"</span><span class="token punctuation">,</span><span class="token string">".jpg"</span><span class="token punctuation">,</span><span class="token string">".jpge"</span><span class="token punctuation">]</span> <span class="token comment">#可以添加任意后缀到列表中</span>
    <span class="token keyword">for</span> i <span class="token keyword">in</span> suffix<span class="token punctuation">:</span>
        <span class="token keyword">if</span> i <span class="token keyword">not</span> <span class="token keyword">in</span> path<span class="token punctuation">:</span>
            <span class="token keyword">continue</span>
        pos<span class="token operator">=</span>path<span class="token punctuation">.</span>find<span class="token punctuation">(</span>i<span class="token punctuation">)</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span>path<span class="token punctuation">[</span>pos<span class="token punctuation">:</span>pos<span class="token operator">+</span><span class="token builtin">len</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
suffix<span class="token punctuation">(</span>url<span class="token punctuation">)</span>
输出<span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span><span class="token operator">-</span>
<span class="token punctuation">.</span>png
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


