export const data = JSON.parse("{\"key\":\"v-a81dc0b4\",\"path\":\"/Blog/2022/Crawl/TianMaoCrawl.html\",\"title\":\"猫眼Top100榜单第1页数据爬取\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"猫眼Top100榜单第1页数据爬取\",\"date\":\"2022-11-28T12:04:21.000Z\",\"author\":\"cava\",\"isOriginal\":true,\"category\":[\"notebook\"],\"tag\":[\"爬虫技术 猫眼电影\"],\"icon\":\"vue\",\"sticky\":false,\"star\":false,\"password\":false,\"article\":true,\"timeline\":true,\"image\":false,\"navbar\":true,\"sidebarIcon\":true,\"headerDepth\":5,\"comment\":true,\"lastUpdated\":true,\"editLink\":false,\"backToTop\":true,\"toc\":true,\"summary\":\"猫眼Top100榜第1页数据爬取 1.流程图 2.代码 2.1请求网站 2.2执行请求 状态码为200则是请求成功 response.text返回响应的内容以文本形式编码 2.3解析器 解析正在获取到的url（获取到\\\"offset=\\\"后的参数），后续以此参数名作为文件名保存 2.4 验证URL 请求的url是否已经存在于目录文件中，将文件下的所有目录文件整合\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://augwewe.cn/Blog/2022/Crawl/TianMaoCrawl.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"augwewe\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"猫眼Top100榜单第1页数据爬取\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"cava\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"爬虫技术 猫眼电影\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-11-28T12:04:21.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"1.流程图\",\"slug\":\"_1-流程图\",\"link\":\"#_1-流程图\",\"children\":[]},{\"level\":2,\"title\":\"2.代码\",\"slug\":\"_2-代码\",\"link\":\"#_2-代码\",\"children\":[{\"level\":3,\"title\":\"2.1请求网站\",\"slug\":\"_2-1请求网站\",\"link\":\"#_2-1请求网站\",\"children\":[]},{\"level\":3,\"title\":\"2.2执行请求\",\"slug\":\"_2-2执行请求\",\"link\":\"#_2-2执行请求\",\"children\":[]},{\"level\":3,\"title\":\"2.3解析器\",\"slug\":\"_2-3解析器\",\"link\":\"#_2-3解析器\",\"children\":[]},{\"level\":3,\"title\":\"2.4 验证URL\",\"slug\":\"_2-4-验证url\",\"link\":\"#_2-4-验证url\",\"children\":[]},{\"level\":3,\"title\":\"2.5 保存文件\",\"slug\":\"_2-5-保存文件\",\"link\":\"#_2-5-保存文件\",\"children\":[]},{\"level\":3,\"title\":\"2.6\\\"引擎\\\"\",\"slug\":\"_2-6-引擎\",\"link\":\"#_2-6-引擎\",\"children\":[]},{\"level\":3,\"title\":\"2.7 完整代码\",\"slug\":\"_2-7-完整代码\",\"link\":\"#_2-7-完整代码\",\"children\":[]}]},{\"level\":2,\"title\":\"3.补充知识点\",\"slug\":\"_3-补充知识点\",\"link\":\"#_3-补充知识点\",\"children\":[{\"level\":3,\"title\":\"3.1 补充 os\",\"slug\":\"_3-1-补充-os\",\"link\":\"#_3-1-补充-os\",\"children\":[]},{\"level\":3,\"title\":\"3.2获取文件下的目录文件名\",\"slug\":\"_3-2获取文件下的目录文件名\",\"link\":\"#_3-2获取文件下的目录文件名\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.6,\"words\":779},\"filePathRelative\":\"Blog/2022/Crawl/TianMaoCrawl.md\",\"localizedDate\":\"2022年11月28日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
