export const data = JSON.parse("{\"key\":\"v-38968456\",\"path\":\"/Blog/2022/Crawl/TianMaoAnalysi.html\",\"title\":\"猫眼Top100榜单分析-进阶\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"猫眼Top100榜单分析-进阶\",\"date\":\"2022-10-30T12:04:21.000Z\",\"author\":\"cava\",\"isOriginal\":true,\"category\":[\"notebook\"],\"tag\":[\"爬虫技术 猫眼电影\"],\"icon\":\"vue\",\"sticky\":false,\"star\":false,\"password\":false,\"article\":true,\"timeline\":true,\"image\":false,\"navbar\":true,\"sidebarIcon\":true,\"headerDepth\":5,\"comment\":true,\"lastUpdated\":true,\"editLink\":false,\"backToTop\":true,\"toc\":true,\"summary\":\"猫眼Top100榜网页分析--进阶：优化代码；解析网页操作（部分） 1.验证获取的URL是否已经请求 1.请求中（ing） 2.刚请求过（ed) 3.已经存在于askingurllist中 1.1定义askingurllist, 请求过的url存放于此列表中 1.2验证url 2. 是否存在文件\\\"html\\\" 2.1代码 3.解析url 3.1path 3.2\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://augwewe.cn/Blog/2022/Crawl/TianMaoAnalysi.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"augwewe\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"猫眼Top100榜单分析-进阶\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"cava\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"爬虫技术 猫眼电影\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-10-30T12:04:21.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"1.验证获取的URL是否已经请求\",\"slug\":\"_1-验证获取的url是否已经请求\",\"link\":\"#_1-验证获取的url是否已经请求\",\"children\":[{\"level\":3,\"title\":\"1.1定义asking_url_list, 请求过的url存放于此列表中\",\"slug\":\"_1-1定义asking-url-list-请求过的url存放于此列表中\",\"link\":\"#_1-1定义asking-url-list-请求过的url存放于此列表中\",\"children\":[]},{\"level\":3,\"title\":\"1.2验证url\",\"slug\":\"_1-2验证url\",\"link\":\"#_1-2验证url\",\"children\":[]}]},{\"level\":2,\"title\":\"2. 是否存在文件\\\"html\\\"\",\"slug\":\"_2-是否存在文件-html\",\"link\":\"#_2-是否存在文件-html\",\"children\":[{\"level\":3,\"title\":\"2.1代码\",\"slug\":\"_2-1代码\",\"link\":\"#_2-1代码\",\"children\":[]}]},{\"level\":2,\"title\":\"3.解析url\",\"slug\":\"_3-解析url\",\"link\":\"#_3-解析url\",\"children\":[{\"level\":3,\"title\":\"3.1path\",\"slug\":\"_3-1path\",\"link\":\"#_3-1path\",\"children\":[]},{\"level\":3,\"title\":\"3.2解析url\",\"slug\":\"_3-2解析url\",\"link\":\"#_3-2解析url\",\"children\":[]}]},{\"level\":2,\"title\":\"4.\\\" 引擎\\\"\",\"slug\":\"_4-引擎\",\"link\":\"#_4-引擎\",\"children\":[]},{\"level\":2,\"title\":\"5.捕获url,定义保存文件名格式\",\"slug\":\"_5-捕获url-定义保存文件名格式\",\"link\":\"#_5-捕获url-定义保存文件名格式\",\"children\":[]}],\"readingTime\":{\"minutes\":1.87,\"words\":562},\"filePathRelative\":\"Blog/2022/Crawl/TianMaoAnalysi.md\",\"localizedDate\":\"2022年10月30日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
