<template><div><h2 id="python-基础练习" tabindex="-1"><a class="header-anchor" href="#python-基础练习" aria-hidden="true">#</a> python 基础练习</h2>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token comment">#Q1----------------------------------</span>
a<span class="token operator">=</span><span class="token string">"snout"</span><span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">:</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>a<span class="token punctuation">)</span>
<span class="token comment">#输出"out"</span>
b<span class="token operator">=</span><span class="token builtin">sorted</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'fog'</span><span class="token punctuation">,</span><span class="token string">'cog'</span><span class="token punctuation">,</span><span class="token string">'dog'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>b<span class="token punctuation">)</span>
<span class="token comment">#输出['cog', 'dog', 'fog']</span>
c<span class="token operator">=</span><span class="token punctuation">(</span><span class="token string">'now'</span><span class="token punctuation">[</span><span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token operator">+</span><span class="token string">'south'</span><span class="token punctuation">[</span><span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token operator">+</span><span class="token string">'hurry'</span><span class="token punctuation">[</span><span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>c<span class="token punctuation">)</span>
<span class="token comment">#输出"why"</span>
d<span class="token operator">=</span><span class="token builtin">sorted</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'owls'</span><span class="token punctuation">:</span><span class="token string">'good'</span><span class="token punctuation">,</span><span class="token string">'more owls'</span><span class="token punctuation">:</span><span class="token string">'not so good'</span><span class="token punctuation">}</span><span class="token punctuation">.</span>values<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>d<span class="token punctuation">)</span>
<span class="token comment">#输出"not so good"</span>
f<span class="token operator">=</span><span class="token builtin">sorted</span><span class="token punctuation">(</span><span class="token string">"cinema"</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>f<span class="token punctuation">)</span>
f1<span class="token operator">=</span><span class="token string">"nic"</span> <span class="token keyword">not</span> <span class="token keyword">in</span> f
<span class="token keyword">print</span><span class="token punctuation">(</span>f1<span class="token punctuation">)</span>
<span class="token comment">#输出True</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token punctuation">[</span>i<span class="token operator">%</span><span class="token number">2</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span><span class="token number">10</span><span class="token punctuation">,</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token comment">#输出[]</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


