<template><div><h2 id="xls-xlsx" tabindex="-1"><a class="header-anchor" href="#xls-xlsx" aria-hidden="true">#</a> xls&amp;xlsx</h2>
<p>一、.xls中最多存入的数据条数：column(256),row(65536)</p>
<p>二、建立.xlsx文件案例步骤</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">import</span> xlxswriter
wb<span class="token operator">=</span>xlsxwriter<span class="token punctuation">.</span>Workbook<span class="token punctuation">(</span><span class="token string">"插入数据xlsxwriter.xlsx"</span><span class="token punctuation">)</span>
<span class="token comment">#可以直接定义文件名</span>
data<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">"date"</span><span class="token punctuation">,</span><span class="token string">"data1"</span><span class="token punctuation">,</span><span class="token string">"data2"</span><span class="token punctuation">]</span>
work_sheet1<span class="token operator">=</span>wb<span class="token punctuation">.</span>add_worksheet<span class="token punctuation">(</span><span class="token string">"代码操作记录"</span><span class="token punctuation">)</span>
<span class="token comment">#定义表格名称</span>
work_sheet1<span class="token punctuation">.</span>write_row<span class="token punctuation">(</span><span class="token string">"A1"</span><span class="token punctuation">,</span>data<span class="token punctuation">)</span>
<span class="token comment">#从第一行第一列的第一格单元格输入数据</span>
data2<span class="token operator">=</span><span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token string">"2022-{i}"</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>i<span class="token operator">=</span>i<span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">13</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">101</span><span class="token punctuation">)</span> <span class="token keyword">for</span> _ <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">101</span><span class="token punctuation">)</span> <span class="token keyword">for</span> _ <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
work_sheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">"A2"</span><span class="token punctuation">,</span>data2<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token comment">#从第一行第一列的第二个单元格输入输入，以填充列的形式</span>
work_sheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">"B2"</span><span class="token punctuation">,</span>data2<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
work_sheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">"C2"</span><span class="token punctuation">,</span>data2<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token comment">#1.折线图定义</span>
chart_col<span class="token operator">=</span>wb<span class="token punctuation">.</span>add_chart<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"type"</span><span class="token punctuation">:</span><span class="token string">"line"</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token comment">#2.给图表设置格式且填充内容</span>
<span class="token comment">#第一条数据data1</span>
chart_col<span class="token punctuation">.</span>add_series<span class="token punctuation">(</span>
    <span class="token punctuation">{</span>
        <span class="token string">"name"</span><span class="token punctuation">:</span><span class="token string">"=代码操作记录!$B$1"</span><span class="token punctuation">,</span><span class="token comment">#b1</span>
        <span class="token string">"categories"</span><span class="token punctuation">:</span><span class="token string">"=代码操作记录!$A$2:$A$7"</span><span class="token punctuation">,</span>
        <span class="token string">"values"</span><span class="token punctuation">:</span><span class="token string">"=代码操作记录!$B$2:$B$7"</span><span class="token punctuation">,</span>
        <span class="token string">"line"</span><span class="token punctuation">:</span><span class="token punctuation">{</span>
            <span class="token string">"color"</span><span class="token punctuation">:</span><span class="token string">"blue"</span><span class="token punctuation">,</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">)</span>
<span class="token comment">#data2</span>
chart_col<span class="token punctuation">.</span>add_series<span class="token punctuation">(</span>
    <span class="token punctuation">{</span>
        <span class="token string">"name"</span><span class="token punctuation">:</span><span class="token string">"=代码操作记录!$C$1"</span><span class="token punctuation">,</span>
        <span class="token string">"categories"</span><span class="token punctuation">:</span><span class="token string">"=代码操作记录!$A$2:$A$7"</span><span class="token punctuation">,</span>
        <span class="token string">"values"</span><span class="token punctuation">:</span><span class="token string">"=代码操作记录!$C$2:$C$7"</span><span class="token punctuation">,</span>
        <span class="token string">"line"</span><span class="token punctuation">:</span><span class="token punctuation">{</span>
            <span class="token string">"color"</span><span class="token punctuation">:</span><span class="token string">"red"</span><span class="token punctuation">,</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">)</span>
<span class="token comment">#3.设置图表插入在表格中的具体位置</span>
chart_col<span class="token punctuation">.</span>set_title<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"name"</span><span class="token punctuation">:</span><span class="token string">"虚假数据折线图"</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
chart_col<span class="token punctuation">.</span>set_x_axis<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"name"</span><span class="token punctuation">:</span><span class="token string">"横坐标"</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
chart_col<span class="token punctuation">.</span>set_y_axis<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"name"</span><span class="token punctuation">:</span><span class="token string">"纵坐标"</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
work_sheet1<span class="token punctuation">.</span>insert_chart<span class="token punctuation">(</span><span class="token string">"D2"</span><span class="token punctuation">,</span>chart_col<span class="token punctuation">,</span><span class="token punctuation">{</span><span class="token string">"x_offset"</span><span class="token punctuation">:</span><span class="token number">20</span><span class="token punctuation">,</span><span class="token string">"y_offset"</span><span class="token punctuation">:</span><span class="token number">20</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
wb<span class="token punctuation">.</span>close<span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


