<template><div><p>猫眼Top100榜网页分析--进阶：优化代码；解析网页操作（部分）</p>
<h3 id="_1-解析url内容优化" tabindex="-1"><a class="header-anchor" href="#_1-解析url内容优化" aria-hidden="true">#</a> 1.解析url内容优化</h3>
<p>将解析后的网页数据保存为字典格式，自定义数据标签为key，内容为value</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">parse</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span>content<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># print(content)</span>
        k_clean <span class="token operator">=</span> re<span class="token punctuation">.</span>sub<span class="token punctuation">(</span><span class="token string">'&lt;/i>&lt;i class="fraction">'</span><span class="token punctuation">,</span> <span class="token string">""</span><span class="token punctuation">,</span> content<span class="token punctuation">)</span><span class="token comment">#先替换，方便提取评分数据</span>
        pattern<span class="token operator">=</span><span class="token string">'&lt;dd>(?:\s+)&lt;i class=.*?&lt;/i>(?:\s+)&lt;a href="(.*?)".*?title="(.*?)".*?>(?:\s+)&lt;img src.*?/>(?:\s+)&lt;img data-src="(.*?)".*?/>'</span> \
                <span class="token string">'*\s?.*?&lt;p class="releasetime">(.*?)&lt;/p>.*?&lt;/div>(?:\s+).*?(?:\s+)&lt;p class="score".*?"integer">(\d\.\d).*?&lt;/p>'</span>
        data_lst<span class="token operator">=</span>re<span class="token punctuation">.</span>findall<span class="token punctuation">(</span>pattern<span class="token punctuation">,</span>k_clean<span class="token punctuation">,</span>re<span class="token punctuation">.</span>S<span class="token punctuation">)</span>
        <span class="token comment"># print(data_lst)#存放链接信息的列表，列表元素是元组：电影名称，电影封面，上映日期，评分</span>
        <span class="token comment"># print(k_clean)</span>
        good_lst<span class="token operator">=</span><span class="token punctuation">[</span><span class="token punctuation">]</span>
        <span class="token keyword">if</span> data_lst<span class="token punctuation">:</span>
            <span class="token keyword">for</span> tup <span class="token keyword">in</span> data_lst<span class="token punctuation">:</span>
                d<span class="token operator">=</span><span class="token punctuation">{</span>
                    <span class="token string">"link"</span><span class="token punctuation">:</span>urllib<span class="token punctuation">.</span>parse<span class="token punctuation">.</span>urljoin<span class="token punctuation">(</span>self<span class="token punctuation">.</span>BASE_URL<span class="token punctuation">,</span> tup<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
                    <span class="token string">"title"</span><span class="token punctuation">:</span>tup<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
                    <span class="token string">"img"</span><span class="token punctuation">:</span>tup<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
                    <span class="token string">"relesstime"</span><span class="token punctuation">:</span>tup<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
                    <span class="token string">"score"</span><span class="token punctuation">:</span>tup<span class="token punctuation">[</span><span class="token number">4</span><span class="token punctuation">]</span>
                <span class="token punctuation">}</span>
                good_lst<span class="token punctuation">.</span>append<span class="token punctuation">(</span>d<span class="token punctuation">)</span>
        <span class="token keyword">return</span>  good_lst
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-将解析后的url内容存储为json格式" tabindex="-1"><a class="header-anchor" href="#_2-将解析后的url内容存储为json格式" aria-hidden="true">#</a> 2.将解析后的url内容存储为JSON格式</h3>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">save_json</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span>content_dict<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token keyword">with</span> <span class="token builtin">open</span><span class="token punctuation">(</span><span class="token string">"TopData"</span><span class="token punctuation">,</span><span class="token string">"w"</span><span class="token punctuation">,</span>encoding<span class="token operator">=</span><span class="token string">"utf-8"</span><span class="token punctuation">)</span> <span class="token keyword">as</span> f<span class="token punctuation">:</span>
        json<span class="token punctuation">.</span>dump<span class="token punctuation">(</span>content_dict<span class="token punctuation">,</span>f<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-运行解析" tabindex="-1"><a class="header-anchor" href="#_3-运行解析" aria-hidden="true">#</a> 3.运行解析</h3>
<p>定义json文件的名称</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">run_parse</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span>folder<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment">#进行排序</span>
        JSON_TXT<span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">"MaoYanTop100"</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">}</span>
        <span class="token comment"># result_list=[]</span>
        <span class="token keyword">for</span> path <span class="token keyword">in</span> <span class="token builtin">sorted</span><span class="token punctuation">(</span>self<span class="token punctuation">.</span>generate_path<span class="token punctuation">(</span>folder<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
            html_content <span class="token operator">=</span> self<span class="token punctuation">.</span>read_html<span class="token punctuation">(</span>path<span class="token punctuation">)</span>
            n<span class="token operator">=</span>self<span class="token punctuation">.</span>parse<span class="token punctuation">(</span>html_content<span class="token punctuation">)</span>
            <span class="token comment"># print(list(n))</span>
            JSON_TXT<span class="token punctuation">[</span><span class="token string">"MaoYanTop100"</span><span class="token punctuation">]</span><span class="token punctuation">.</span>append<span class="token punctuation">(</span><span class="token builtin">list</span><span class="token punctuation">(</span>n<span class="token punctuation">)</span><span class="token punctuation">)</span>
            self<span class="token punctuation">.</span>save_json<span class="token punctuation">(</span>JSON_TXT<span class="token punctuation">)</span>
        pprint<span class="token punctuation">(</span>JSON_TXT<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


