export const data = JSON.parse("{\"key\":\"v-5ff095e6\",\"path\":\"/Blog/2022/Crawl/foundation/rule.html\",\"title\":\"正则表达式\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"正则表达式\",\"date\":\"2022-10-30T12:04:21.000Z\",\"author\":\"cava\",\"isOriginal\":true,\"category\":[\"notebook\",\"VuePress\"],\"tag\":[\"Vue\",\"VuePress\"],\"icon\":\"vue\",\"sticky\":false,\"star\":false,\"password\":false,\"article\":true,\"timeline\":true,\"image\":false,\"navbar\":true,\"sidebarIcon\":true,\"headerDepth\":5,\"comment\":true,\"lastUpdated\":true,\"editLink\":false,\"backToTop\":true,\"toc\":true,\"summary\":\"正则表达式 模式 模式 描述 | -------- ------------------------------------------------------------ | \\\\w 匹配字母数字及下划线 | \\\\W 匹配非字母数字下划线 | \\\\s 匹配任意空白字符，等价于 [\\\\t\\\\n\\\\r\\\\f]. | \\\\S 匹配任意非空字符 | \\\\d 匹配任意数字，等价于 [\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://augwewe.cn/Blog/2022/Crawl/foundation/rule.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"augwewe\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"正则表达式\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"cava\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Vue\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"VuePress\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-10-30T12:04:21.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"正则表达式\",\"slug\":\"正则表达式\",\"link\":\"#正则表达式\",\"children\":[{\"level\":3,\"title\":\"模式\",\"slug\":\"模式\",\"link\":\"#模式\",\"children\":[]},{\"level\":3,\"title\":\"常规匹配\",\"slug\":\"常规匹配\",\"link\":\"#常规匹配\",\"children\":[]},{\"level\":3,\"title\":\"atttention:\",\"slug\":\"atttention\",\"link\":\"#atttention\",\"children\":[]},{\"level\":3,\"title\":\"泛匹配\",\"slug\":\"泛匹配\",\"link\":\"#泛匹配\",\"children\":[]},{\"level\":3,\"title\":\"匹配特定目标\",\"slug\":\"匹配特定目标\",\"link\":\"#匹配特定目标\",\"children\":[]},{\"level\":3,\"title\":\"贪婪匹配\",\"slug\":\"贪婪匹配\",\"link\":\"#贪婪匹配\",\"children\":[]},{\"level\":3,\"title\":\"换行输出\",\"slug\":\"换行输出\",\"link\":\"#换行输出\",\"children\":[]},{\"level\":3,\"title\":\"groups()返回所有\",\"slug\":\"groups-返回所有\",\"link\":\"#groups-返回所有\",\"children\":[]},{\"level\":3,\"title\":\"转义 - 原样输出特殊符号\",\"slug\":\"转义-原样输出特殊符号\",\"link\":\"#转义-原样输出特殊符号\",\"children\":[]},{\"level\":3,\"title\":\"search方法\",\"slug\":\"search方法\",\"link\":\"#search方法\",\"children\":[]},{\"level\":3,\"title\":\"sub方法\",\"slug\":\"sub方法\",\"link\":\"#sub方法\",\"children\":[]},{\"level\":3,\"title\":\"正则表达式小测试\",\"slug\":\"正则表达式小测试\",\"link\":\"#正则表达式小测试\",\"children\":[]},{\"level\":3,\"title\":\"excel数据清洗小案例\",\"slug\":\"excel数据清洗小案例\",\"link\":\"#excel数据清洗小案例\",\"children\":[]}]}],\"readingTime\":{\"minutes\":5.66,\"words\":1697},\"filePathRelative\":\"Blog/2022/Crawl/foundation/rule.md\",\"localizedDate\":\"2022年10月30日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
