export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"title":"关于博主","icon":"home","type":"article","readingTime":{"minutes":0.15,"words":44},"excerpt":"Intro Page Place your introducation and profile here.","date":"2022-09-04T12:11:00.000Z","localizedDate":"2022年9月4日"},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"title":"augwewe","icon":"home","type":"home","readingTime":{"minutes":0.38,"words":115},"excerpt":""},["/index.html","/README.md"]],
  ["v-711c2fc6","/Blog/2022/mywriter.html",{"title":"python 自动化","icon":"vue","type":"article","readingTime":{"minutes":1.19,"words":357},"excerpt":"","author":"cava","date":"2022-10-30T12:04:21.000Z","localizedDate":"2022年10月30日","category":["notebook","VuePress"],"tag":["Vue","VuePress"],"sticky":false,"star":false,"isOriginal":true,"isEncrypted":true},["/Blog/2022/mywriter","/Blog/2022/mywriter.md"]],
  ["v-2a67d123","/Blog/2022/mywriter2.html",{"title":"python Note","icon":"vue","type":"article","readingTime":{"minutes":0.46,"words":137},"excerpt":"python 基础练习","author":"cava","date":"2022-10-30T12:04:21.000Z","localizedDate":"2022年10月30日","category":["notebook","VuePress"],"tag":["Vue","VuePress"],"sticky":false,"star":false,"isOriginal":true},["/Blog/2022/mywriter2","/Blog/2022/mywriter2.md"]],
  ["v-0f102de0","/Blog/2022/rule.html",{"title":"正则表达式","icon":"vue","type":"article","readingTime":{"minutes":1.29,"words":386},"excerpt":"正则表达式 模式 常规匹配 atttention: re.match(pattern,string,flag=0) 从字符的起始位置匹配一个模式，如果不是起始位置匹配成功,match()返回none \\w只能匹配到一个数字/字母 泛匹配 匹配特定目标 贪婪匹配","author":"cava","date":"2022-10-30T12:04:21.000Z","localizedDate":"2022年10月30日","category":["notebook","VuePress"],"tag":["Vue","VuePress"],"sticky":false,"star":false,"isOriginal":true},["/Blog/2022/rule","/Blog/2022/rule.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"文章","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"加密","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"幻灯片","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"收藏","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"时间轴","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-3847fc9c","/category/notebook/",{"title":"notebook 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/notebook/index.html"]],
  ["v-b302da92","/tag/vue/",{"title":"Vue 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/vue/index.html"]],
  ["v-43d7543a","/category/vuepress/",{"title":"VuePress 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/vuepress/index.html"]],
  ["v-ed16b278","/tag/vuepress/",{"title":"VuePress 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/vuepress/index.html"]],
]
